### ISSUE TITLE
error in transpile

### ISSUE THREAD

**Issue by josselinchevalay** [AkashaProject/ipfs-connector#1]
Hi, 

i try to use your project but i have a issue when use tsc command to transpile my project. 

```bash 
tsc --version 
version 1.8.10
``` 

when try transpile my project a i have ths error 

```
node_modules/@akashaproject/ipfs-connector/src/IpfsApiHelper.d.ts(2,1): error TS1084: Invalid 'reference' directive syntax.
node_modules/@akashaproject/ipfs-connector/src/IpfsApiHelper.d.ts(3,1): error TS1084: Invalid 'reference' directive syntax.
node_modules/@akashaproject/ipfs-connector/src/IpfsApiHelper.d.ts(10,21): error TS1005: '=' expected.
node_modules/@akashaproject/ipfs-connector/src/IpfsApiHelper.d.ts(10,32): error TS1005: ';' expected.
node_modules/@akashaproject/ipfs-connector/src/IpfsApiHelper.d.ts(11,21): error TS1005: '=' expected.
node_modules/@akashaproject/ipfs-connector/src/IpfsApiHelper.d.ts(11,31): error TS1005: ';' expected.
node_modules/@akashaproject/ipfs-connector/src/IpfsApiHelper.d.ts(12,21): error TS1005: '=' expected.
/node_modules/@akashaproject/ipfs-connector/src/IpfsApiHelper.d.ts(12,33): error TS1005: ';' expected.
/node_modules/@akashaproject/ipfs-connector/src/IpfsApiHelper.d.ts(13,21): error TS1005: '=' expected.
/node_modules/@akashaproject/ipfs-connector/src/IpfsApiHelper.d.ts(13,31): error TS1005: ';' expected.
/node_modules/@akashaproject/ipfs-connector/src/IpfsBin.d.ts(2,1): error TS1084: Invalid 'reference' directive syntax.
node_modules/@akashaproject/ipfs-connector/src/IpfsConnector.d.ts(2,1): error TS1084: Invalid 'reference' directive syntax.
node_modules/@akashaproject/ipfs-connector/src/IpfsConnector.d.ts(3,1): error TS1084: Invalid 'reference' directive syntax.
/node_modules/@akashaproject/ipfs-connector/src/IpfsConnector.d.ts(31,14): error TS1005: '=' expected.
node_modules/@akashaproject/ipfs-connector/src/IpfsConnector.d.ts(31,17): error TS1005: ';' expected.
node_modules/@akashaproject/ipfs-connector/typings/main.d.ts(1,29): error TS1005: '{' expected.
node_modules/@akashaproject/ipfs-connector/typings/main.d.ts(2,26): error TS1005: '{' expected.
node_modules/@akashaproject/ipfs-connector/typings/main.d.ts(3,22): error TS1005: '{' expected.
node_modules/@akashaproject/ipfs-connector/typings/main.d.ts(4,25): error TS1005: '{' expected.
``` 

thx in advance for your help. 
your idea is very interesting and i hope solve my needs.

**Comment by kenshyx** [comment]
Hello, you need typescript version specified in package.json(2.0.6). Also run `npm install` before compiling because some of the definition files come from npm and finally you can call `tsc -p tsconfig.json`. Let me know if it worked :)

**Comment by josselinchevalay** [comment]
hi , 

i installed typescript 2.0.6 and i have this type this command 

```
tsc -p tsconfig.json
```
and i have this 
IpfsConnector.d.ts(29,27): error TS2304: Cannot find name 'Symbol'.

**Comment by kenshyx** [comment]
You need node version specified in package.json `"node": ">=6.1.0"`

**Comment by kenshyx** [comment]
Also try with the latest version :D

**Comment by josselinchevalay** [comment]
ok i use gulp-typescript to transpile i think issue cause by this. Any idea ?

**Comment by kenshyx** [comment]
Did you try with the latest release `1.6.11` ? :)

**Comment by josselinchevalay** [comment]
gulp or gulp-trypescript ?

**Comment by kenshyx** [comment]
ipfs-connector `1.6.11`

**Comment by josselinchevalay** [comment]
ok i can transpile my typescript but now i hve an issue with systemjs ...

**Comment by kenshyx** [comment]
You want to use this package from browser?

**Comment by josselinchevalay** [comment]
no for electron application ^

**Comment by kenshyx** [comment]
Ok, from renderer or main process?

**Comment by josselinchevalay** [comment]
renderer

**Comment by kenshyx** [comment]
I don't think it works from renderer :)

**Comment by kenshyx** [comment]
Maybe with node integration on for browserWindow but in production it wont work

**Comment by josselinchevalay** [comment]
i try solve an solution =) 
thx

**Comment by josselinchevalay** [comment]
i find a solution ^^ thx a lot four your help

**Comment by josselinchevalay** [comment]
hi,

i'm sorry but i have a new error. 

when instanciate IPFSconnector  : 

`const ipfsConnectorInstance = IpfsConnector.getInstance();`

i have this stack error

`ERROR in ./~/@akashaproject/ipfs-connector/src/IpfsConnector.js
Module not found: Error: Cannot resolve module 'child_process' in /media/dev/telescope/node_modules/@akashaproject/ipfs-connector/src
 @ ./~/@akashaproject/ipfs-connector/src/IpfsConnector.js 8:21-45

ERROR in ./~/@akashaproject/ipfs-connector/src/IpfsBin.js
Module not found: Error: Cannot resolve module 'fs' in /media/dev/telescope/node_modules/@akashaproject/ipfs-connector/src
 @ ./~/@akashaproject/ipfs-connector/src/IpfsBin.js 3:13-26

ERROR in ./~/bin-wrapper/index.js
Module not found: Error: Cannot resolve module 'fs' in /media/dev/telescope/node_modules/bin-wrapper
 @ ./~/bin-wrapper/index.js 3:9-22
`

now i use webpack to bundle my application with typescript 2 node js 6  webpack 1.13.3 

thx in advance

**Comment by kenshyx** [comment]
fs is a node.js module so I think you need to specify it in webpack config as empty.

**Comment by kenshyx** [comment]
ipfs-connector is designed to work only on main process :)

**Comment by josselinchevalay** [comment]
ok so i must to use ipfs-api ?

**Comment by kenshyx** [comment]
yes, and use a local ipfs daemon

**Comment by josselinchevalay** [comment]
=) now i know :+1:

**Comment by kenshyx** [comment]
ipfs-connector does both, it handles daemon spawning and connects to api
