### ISSUE TITLE
IPFS binary doesn't get updated

### ISSUE THREAD

**Issue by MichaelMure** [AkashaProject/ipfs-connector#10]
After updating ipfs-connector to the latest version I expected it to download a newer version of IPFS since the expected version is different in the new version (0.4.9 instead of 0.4.7).

But that's not the case, IPFS 0.4.7 still get launched.

I guess you use something like this for akasha ?
```javascript
const onServiceStarted = async () => {
  const instance = IpfsConnector.getInstance()
  const versionOK = await instance.checkVersion()

  if(!versionOK) {
    console.log("Need to update IPFS")
    await instance.stop()
    await instance.downloadManager.deleteBin()
    instance.start()
    return
  }
....
}
```

Would it be better to have ipfs-connector deal with this ? It will break with a wrong version for the daemon anyway since you expect a specific API.

**Comment by kenshyx** [comment]
Yes, we're using this approach for akasha, I will include this functionality in the next release.

**Comment by kenshyx** [comment]
Check `1.9.0` :)

**Comment by MichaelMure** [comment]
Nice, thank you :-)
