### ISSUE TITLE
api.apiClient port doesn't get updated after a staticSetPorts()

### ISSUE THREAD

**Issue by MichaelMure** [AkashaProject/ipfs-connector#11]
`js-ipfs-api` is initialized with the first call to IpfsConnector.api() but need to get overwritten after the call to staticSetPorts(). I'm not sure what code path is used, but I end up with `js-ipfs-api` doing call to the default port 5001 instead of the one I set up.

For reference, this is what I use to start the daemon:

```javascript
  const instance = IpfsConnector.getInstance()

  const userDataPath = app.getPath('userData')

  // set the download path for ipfs
  instance.setBinPath(userDataPath)

  // set the repo path
  instance.setIpfsFolder(path.join(userDataPath,'ipfs-repo'))

  // enable some experimental features
  instance.setOption('args', [
    'daemon',
    '--enable-pubsub-experiment'
  ])

  ports = {
    api: await getPort(4280),
    gateway: await getPort(4281),
    swarm: await getPort(4282)
  }

  await instance.staticSetPorts(ports)

  // start ipfs daemon and download binaries if needed
  instance.start()
```

**Comment by kenshyx** [comment]
It's safer to use `setPorts` which calls the correct method(`rpcSetPorts` or `staticSetPorts`) if the ipfs daemon is running or not. Also you can specify the second parameter `setPorts(ports, true)` to restart or start the daemon

**Comment by MichaelMure** [comment]
> It's safer to use setPorts which calls the correct method(rpcSetPorts or staticSetPorts) if the ipfs daemon is running or not.

Good point, thanks.

> Also you can specify the second parameter setPorts(ports, true) to restart or start the daemon

Indeed but that doesn't solve my problem. In my code sample, the api should be set properly after the `start()` but that's not the case. `IpfsConnector._api` should be reset in `IpfsConnector._start()`, otherwise the old port is still used.

**Comment by kenshyx** [comment]
Done :)

**Comment by MichaelMure** [comment]
Great !

... sadly one of my unsolved problem reemerge if I try to change a port...

In my project I actually have *two* instances of ipfs-connector (not on purpose mind you). One in the electron main process, and one in the renderer process. It worked until now because the config was the same in both instance.

I wrote some more details here: https://github.com/MichaelMure/TotallyNotArbore/blob/e0d190e8aa1af9f11d207661f91a1a07182dc894/app/ipfs/ipfsMain.js#L7

How do you deal with this problem for Akasha ?

**Comment by kenshyx** [comment]
We use ipfs-connector just in main process. When the renderer needs something from ipfs it calls an electron ipc channel(something similar to rest) and the main process will process the request and it sends back to renderer the result.

**Comment by MichaelMure** [comment]
I see, so you still have redux in the renderer only. No plan for having Akasha running in the background with a tray icon ?

**Comment by kenshyx** [comment]
You mean the react-redux logic? The background task functionality can be emulated using `Tray` from electron by toggling `BrowserWindow` visibility.

**Comment by MichaelMure** [comment]
I mean the redux store. To have a main window and a tray icon, you would need to have the store state replicated between these two renderer process, or more conveniently having a master redux store in the main process and synchronize the state with the two renderer.

I still have to figure out how to do all that ... 

> When the renderer needs something from ipfs it calls an electron ipc channel(something similar to rest) and the main process will process the request and it sends back to renderer the result.

Do you use [electron remote](https://github.com/electron/electron/blob/master/docs/api/remote.md) ? Or is it a custom implementation with ipcMain/IpcRenderer ? A code sample would be really helpful if it's possible for Akasha.

**Comment by kenshyx** [comment]
Electron remote is very bad for performance, I won't recommend using it. We're using a thin wrapper over ipc for communication between main and renderer using some predefined channels injected from preloader.
