### ISSUE TITLE
Download progress feedback

### ISSUE THREAD

**Issue by MichaelMure** [AkashaProject/ipfs-connector#15]
It would be nice to have access to the download progression for user feedback (download slow or stalled ...).

I looked at this a while ago without finding an obvious way, but maybe with a fork of bin-wrapper it would be doable (maybe https://github.com/simonepri/bin-manager ?).

**Comment by kenshyx** [comment]
Check latest version `v1.10.0` :)

**Comment by MichaelMure** [comment]
Ho nice ! Thank you !

Just a nitpick here: https://github.com/AkashaProject/ipfs-connector/commit/6e4ad4bab382f2008d1971f734523301368cf4b3#commitcomment-23068781

Totally unrelated, but do you have a rule against async/await code instead of callbacks and Promise chain ? I felt it's really easier to write and to cover all cases properly.

**Comment by kenshyx** [comment]
> Totally unrelated, but do you have a rule against async/await code instead of callbacks and Promise chain ? I felt it's really easier to write and to cover all cases properly.

Not rly, the problem is that it will require node > v7.6 for default support

**Comment by MichaelMure** [comment]
Humm, for the progress event, I get an array instead of a number for the total:
```json
{
   "completed":8564736,
   "resource":"https://dist.ipfs.io/go-ipfs/v0.4.10/go-ipfs_v0.4.10_linux-amd64.tar.gz",
   "total":[
      "8580949"
   ]
}
```

Do you have the same thing ? Not the end of the world, but well ...

**Comment by kenshyx** [comment]
Interesting, I have a specific test which passed https://github.com/AkashaProject/bin-wrapper-progress/blob/master/tests.ts#L29 for that. It seems the web server changed the response header and it requires some normalization right now, will do it today.

**Comment by MichaelMure** [comment]
FYI, I still need some special code to handle this small problem: https://github.com/MichaelMure/Arbore/blob/master/app/components/IpfsStatus.js#L40-L45

The `remove all that` is never triggered, but I've no idea where this comes from.
