### ISSUE TITLE
go-ipfs v0.4.14-rc1

### ISSUE THREAD

**Issue by MichaelMure** [AkashaProject/ipfs-connector#16]
Hello,

Could you make a release with the new go-ipfs v0.4.14-rc1 ?

Thank you !

**Comment by kenshyx** [comment]
Hello, I can make a release only when v0.4.14-rc1 is published at https://dist.ipfs.io/

**Comment by MichaelMure** [comment]
It's now available at https://dist.ipfs.io/go-ipfs/v0.4.14-rc1

**Comment by kenshyx** [comment]
Released v1.10.20, there might be some problems with the shutdown command on this version.

**Comment by kenshyx** [comment]
Also there are some random 404 errors when trying to download.

**Comment by kenshyx** [comment]
Use with caution

**Comment by MichaelMure** [comment]
Thank you !
