### ISSUE TITLE
TypeError: IpfsConnector.getInstance is not a function

### ISSUE THREAD

**Issue by vaibhav6233m** [AkashaProject/ipfs-connector#18]
I want to use IPFS inside my electron application. I tried the sample code snippet, but the execution is failing. Am I missing something here? 

![screenshot from 2018-06-14 19-41-07](https://user-images.githubusercontent.com/29979122/41417842-13e095ba-700c-11e8-8734-97c64d14c219.png)

Output:
![screenshot from 2018-06-14 19-39-58](https://user-images.githubusercontent.com/29979122/41417841-13a63a14-700c-11e8-96eb-91a54b786bc6.png)

**Comment by kenshyx** [comment]
Hey, thanks for trying out the lib. In example its destructured when importing
 ```import { IpfsConnector } from '@akashaproject/ipfs-connector';```. 
So in your case if you want to use `require`:
```
const IpfsConnector = require('@akashaproject/ipfs-connector').IpfsConnector
```

**Comment by vaibhav6233m** [comment]
Hi @kenshyx, thanks a lot for pointing that out. It is working now.
