### ISSUE TITLE
Misleading example

### ISSUE THREAD

**Issue by MichaelMure** [AkashaProject/ipfs-connector#3]
The example in the readme say that:
```javascript
// start ipfs daemon and download binaries if needed
instance.start().then(...);
```
The `.then(...)` part led me to think that IPFS was ready at that point. Actually the promise resolve as soon as the binary is spawned, so the API is not ready at this point and will throw an error.

What you need to do is to install some listener like this:
```javascript
instance.on(ipfsEvents.SERVICE_STARTED, onServiceStarted)
```
Maybe the start() promise should resolve once the API is available ?

**Comment by kenshyx** [comment]
Hello, the readme is outdated. I will include in the next release this update :)

**Comment by MichaelMure** [comment]
Thank you for the release.

Sure you don't want to release Akasha as well ? ;)
