### ISSUE TITLE
Offline port configuration for IPFS daemon

### ISSUE THREAD

**Issue by MichaelMure** [AkashaProject/ipfs-connector#5]
Currently, IPFS need to be started to change the port configuration but that cause problem when one of the port are already in use.

IPFS allow to change the port through the ipfs binary, when the daemon is not running:

```
// Change the api port config
ipfs config Addresses.API /ip4/127.0.0.1/tcp/5003

// Disable the gateway
ipfs config Addresses.Gateway ''
```

This could even be made config-less by using something like https://github.com/daaku/nodejs-freeport to find a free port.

**Comment by MichaelMure** [comment]
I might work on this in the future but it's not yet my priority. I'm just leaving this here as it seems to be a problem for Akasha as well.

**Comment by kenshyx** [comment]
This is inconsistent on windows, it requires an api available.

**Comment by MichaelMure** [comment]
Ho really ?

I just tried on a Windows 8 and it works properly. For the gateway, I juste had to change to this version, that works on linux as well:

```
// Disable the gateway
ipfs config Addresses.Gateway ""
```

**Comment by kenshyx** [comment]
It doesn't work on non-dev enviroment, I had a previous version using this.

**Comment by kenshyx** [comment]
It's still inconsistent, on my local environment it works but on travis it fails @MichaelMure https://travis-ci.org/AkashaProject/ipfs-connector/builds/226425114#L3127

**Comment by kenshyx** [comment]
Closing for now, you can try `1.8.2`.

**Comment by MichaelMure** [comment]
Thanks :)
