### ISSUE TITLE
conditional dependencies ?

### ISSUE THREAD

**Issue by MichaelMure** [AkashaProject/ipfs-connector#8]
The last version of ipfs-connector has `js-ipfs` as a dependency, even if I would like to use only go-ipfs. A nice thing would be to be able to choose the ipfs implementation.

On a side note, this is currently a problem for me because of a error in one of the dependencies that ultimately pull react (!) and break my app. I filed an issue there: https://github.com/ipld/js-ipld-eth-storage-trie/issues/3

```
└─┬ @akashaproject/ipfs-connector@1.8.2
   └─┬ ipfs@0.23.1
      └─┬ ipld-resolver@0.11.0
         └─┬ ipld-eth-storage-trie@1.0.1
            └─┬ aegir@9.4.0
               └─┬ clean-documentation-theme@0.4.2
                  └── react@15.5.4 
```

**Comment by MichaelMure** [comment]
It could be done like this: https://softwareengineering.stackexchange.com/a/273576

**Comment by kenshyx** [comment]
Hello, next version will have separated package for each ipfs implementation.

**Comment by MichaelMure** [comment]
Awesome :)
